backend:
  name: github
  repo: BenCamps/BenCamps.github.io # The name of the repository
  branch: main # Branch to update (optional; defaults to master)

# This line should *not* be indented
# publish_mode: editorial_workflow
publish_mode: simple # Use simple mode for direct publishing without review

# This line should *not* be indented
media_folder: "public/static/images" # Media files will be stored in the repo under public/static/images
public_folder: "/static/images" # The src attribute for uploaded media will begin with /static/images

# https://decapcms.org/docs/configuration-options/#slug-type
slug:
  encoding: 'ascii'
  clean_accents: true
  sanitize_replacement: '_'

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "data/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{year}}-{{month}}-{{day}}_{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Summary", name: "summary", widget: "string" }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list", default: [] }
      - { label: "Last Modified", name: "lastmod", widget: "datetime", required: false }
      - { label: "Images", name: "images", widget: "list", required: false, field: { label: "Image", name: "image", widget: "string" } }
      - { label: "Authors", name: "authors", widget: "list", required: false, field: { label: "Author", name: "author", widget: "string" } }
#      - { label: "Layout", name: "layout", widget: "string", required: false }
      